version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "3000:3000"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    nodeapp1:
        image: safehouse-backend
        environment:
            - APPID=1111
    nodeapp2:
        image: safehouse-backend
        environment:
            - APPID=2222
    nodeapp3:
        image: safehouse-backend
        environment:
            - APPID=3333